name: Python Tests

on:
  push:
    branches: [ main ] # Or your default branch, e.g., master
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"] # Specify your Python version(s)

    steps:
    - uses: actions/checkout@v4
      # Fetches your repository code

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have a requirements.txt file:
        pip install -r requirements.txt
        # If you have other dependencies, install them here
        # e.g., pip install requests geopy streamlit

    - name: Run tests
      run: |
        python -m unittest discover -s tests